image: inovex/gitlab-ci-android

stages:
  - build

variables:
  ANDROID_SDK_ROOT: /Library/Android/sdk
  KEYSTORE_ALIAS: key0
  KEYSTORE_PASSWORD: newrelease
  KEY_PASSWORD: newrelease
  APPLICATION_ID_VERSION_NAME: Pari_quiz_v1_com.paribetqiuz.pari.dep
  TELEGRAM_BOT_TOKEN: 935417338:AAGPfdKDuAYdmo2Myjc-FjLJ6WE6yP0nrJ8
  TELEGRAM_CHAT_ID: -1001871616567
  KEYPASS_FILE: keystore.pass
  KEYSTORE_FILE: keystore.jks
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export ANDROID_HOME=/sdk
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools/34.0.5

  - chmod +x ./gradlew

build:
  stage: build
  script:
    - |
      KEYSTORE_FILE=$CI_PROJECT_DIR/app/keystore.jks
  
      if [ -f $KEYSTORE_FILE ]; then
      echo "File $KEYSTORE_FILE already exists."
      else
      keytool -genkeypair -v -keystore $KEYSTORE_FILE -keyalg RSA -keysize 2048 -validity 10000 -alias $KEYSTORE_ALIAS -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD -dname "CN=John Doe, OU=Dev, O=Company, L=City, ST=State, C=US"
      echo "Created $KEYSTORE_FILE in the app directory."
      fi

    - ./gradlew  assembleRelease
    - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/$APPLICATION_ID_VERSION_NAME.apk
    - ls app/build/outputs/apk/release/
    - ./gradlew  bundleRelease
    - ls app/build/outputs/bundle/release/
    - mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/$APPLICATION_ID_VERSION_NAME.aab


  artifacts:
    name: APPLICATION_ID_VERSION_NAME
    paths:
      - app/build/outputs/apk/release/$APPLICATION_ID_VERSION_NAME.apk
      - app/build/outputs/bundle/release/$APPLICATION_ID_VERSION_NAME.aab
      - app/keystore.jks

  only:
    - master
after_script:
  - |
    MESSAGE="$CI_COMMIT_MESSAGE"
    curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"

    curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@app/build/outputs/bundle/release/$APPLICATION_ID_VERSION_NAME.aab -F text=MESSAGE -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
    curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@app/keystore.jks -F text="Keystore File" -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
    curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@app/build/outputs/apk/release/$APPLICATION_ID_VERSION_NAME.apk -F text=MESSAGE -H "Content-Type: multipart/form-data" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
